### ISSUE TITLE
DBAL-1312: Queries not executed when PDO::ATTR_EMULATE_PREPARES is disabled

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/dbal#1270]
Jira issue originally created by user mnapoli:

It seems that when setting `PDO::ATTR*EMULATE*PREPARES` to false some queries are not executed.

I'm seeing this in Doctrine ORM, but reporting it in DBAL since I believe it might be the correct project. Basically I have an entity:

```
Promotion:
    type: entity
    id:
        id:
            type: guid
    fields:
        active:
            type: boolean
    embedded:
        type:
            class: PromotionType
    oneToMany:
        bonuses:
            targetEntity: Bonus\Bonus
            mappedBy: promotion
            orphanRemoval: true
            cascade: [ all ]
            fetch: EAGER
```

My tests pass. But when I set `PDO::ATTR*EMULATE*PREPARES` to false my tests fail because Doctrine is trying to insert a `Bonus` for a `Promotion` ID that doesn't exist.

So it could be either that Doctrine tries to insert the Bonus first or either that the Promotion failed (silently) to be persisted. After searching through Internet I think this is the second explanation:
- "Doctrine doesn't persist entity with boolean values and PDO::ATTR_EMULATE_PREPARES = false in Mysql" (exactly the same thing as me) http://stackoverflow.com/questions/31089893/doctrine-doesnt-persist-entity-with-boolean-values-and-pdoattr-emulate-prepar
- Same problem again (in french): https://openclassrooms.com/forum/sujet/doctrine-2-attr-emulate-prepares-et-type-booleen

I'm in a rush at work so sorry I don't have time to investigate further :( but it seems there's something going on with the booleans.
