### ISSUE TITLE
DBAL-198: Custom platform is not taken into account

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/dbal#1369]
Jira issue originally created by user sdecleire:

When defining a custom platform in the configuration of Symfony 2 like below :
\

```
services:
    my_platform:
        class: Doctrine\DBAL\Platforms\MyPlatform

doctrine:
    dbal:
         options:
               platform: @my_platform
```

\
the custom platform MyPlatform is not taken into account and the driver default one is used instead.
