### ISSUE TITLE
DBAL-866: Foreign Key Constraints does not work with Doctrine/Symfony and SQLite

### ISSUE THREAD

**Issue by doctrinebot** [doctrine/dbal#2104]
Jira issue originally created by user naitsirch:

I have posted a question on stackoverflow already to get help on this issue, but nobody could give me a sufficient answer. See [here](http://stackoverflow.com/questions/22924444/foreign-key-constraints-does-not-work-with-doctrine-symfony-and-sqlite).

[#370](http://doctrine-project.org/jira/browse/[DBAL-370]%28http://www.doctrine-project.org/jira/browse/DBAL-370%29) says that support for foreign keys support for SQLite has been implemented. But in my case it does not work. I have defined two entities:
\

``` yaml
Category:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        ministries:
            targetEntity: Ministry
            cascade: [persist]
            mappedBy: category
```

And

``` yaml
Ministry:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: ministries
            joinColumn:
                name: category_id
                nullable: false
                onDelete: CASCADE
```

But when I delete a category, the ministry entities do not get deleted, although the constraint should cascade. What am I missing?

Do I have to configure anything to get that working or is it a bug?
