### ISSUE TITLE
OraclePlatorm/OracleSessionInit datetimez format disconnect

### ISSUE THREAD

**Issue by dadamssg** [doctrine/dbal#2332]
I encountered my dates having the wrong offset when using the **datetimetz** type in the orm. I finally tracked it down to the [OracleSessionInit's NLS_TIMESTAMP_TZ_FORMAT](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Event/Listeners/OracleSessionInit.php#L49) session variable being set incorrectly. As you can see it defaults to setting it with a space between the time and the offset while [OraclePlatform class's format does not have a space](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/OraclePlatform.php#L1019).

I fixed this by overriding the arguments passed to OracleSessionInit in my container configuration and everything is working as expected. 

```
services:
    oci8.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        arguments:
            - { NLS_TIMESTAMP_TZ_FORMAT: "YYYY-MM-DD HH24:MI:SSTZH:TZM" }
        tags:
            - { name: doctrine.event_listener, event: postConnect } 
```

It caused my quite the headache and it seems to me that this issue exists across all Oracle versions but i'm not sure. This is the first time I've ever used Oracle. My version info below. 

```
Oracle Database 12c Release 12.1.0.1.0 - 64bit Production
PL/SQL Release 12.1.0.1.0 - Production
"CORE   12.1.0.1.0  Production"
TNS for Linux: Version 12.1.0.1.0 - Production
NLSRTL Version 12.1.0.1.0 - Production
```
