### ISSUE TITLE
Overwriting doctrine slaves connection informations does not works

### ISSUE THREAD

**Issue by jpillias** [doctrine/dbal#2681]
Hi all,

I'm using multiple doctrine dbal connections, and slaves connection.
Here is my standard configuration (using symfony2) :  

```yaml
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8mb4
                server_version: 5.7 # this is workaround, since their is a bug on doctine dbal 2.5
                # see https://github.com/doctrine/DoctrineBundle/issues/351 to see if bug is resolved
                slaves:
                  slaveDefault1:
                    charset:  utf8mb4
                    host:     "%database_host%"
                    port:     "%database_port_read%"
                    dbname:   "%database_name%"
                    user:     "%database_user%"
                    password: "%database_password%"
            client:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                #dbname, username et password sera écrasé par notre service en fonction du client connecté
                dbname:   shouldBeOverwrite #will be overwrite
                user:     "%database_user%" #will be overwrite
                password: "%database_password%" #will be overwrite
                charset:  utf8mb4
                server_version: 5.7 # this is workaround, since their is a bug on doctine dbal 2.5
                slaves:
                  slaveClient1:
                    charset:  utf8mb4
                    host:     "%database_host%"
                    port:     "%database_port_read%"
                    dbname:   shouldBeOverwrite #will be overwrite
                    user:     "%database_user%" #will be overwrite
                    password: "%database_password%" #will be overwrite
```
and in a symfony2 service, i overwrite the "client" connection information : 

```php
$clientConnection = $this->container->get('doctrine.dbal.client_connection');
        $params     = $clientConnection->getParams();

        // we also check if the current connection needs to be closed based on various things
        if ($clientConnection->isConnected()) {
            $clientConnection->close();
        }

        // Set default DB connection using bddName of Compte's user
        $params['dbname'] = $compte->getBddName();
        if($useRootAccount) {
            $params['user'] = $this->mainUser;
            $params['password'] = $this->mainPwd;
            if(isset($params['slaves'])){
                foreach ($params['slaves'] as &$slave){
                    $slave['dbname'] = $compte->getBddName();
                    $slave['user'] = $this->mainUser;
                    $slave['password'] = $this->mainPwd;
                }
            }
            if(isset($params['master'])){
                $params['master']['dbname'] = $compte->getBddName();
                $params['master']['user'] = $this->mainUser;
                $params['master']['password'] = $this->mainPwd;
            }
        }
        else{
            $params['user'] = $compte->getSqlUser();
            $params['password'] = $compte->getSqlPassword();
            if(isset($params['slaves'])){
                foreach ($params['slaves'] as &$slave){
                    $slave['dbname'] = $compte->getBddName();
                    $slave['user'] = $compte->getSqlUser();
                    $slave['password'] = $compte->getSqlPassword();
                }
            }
            if(isset($params['master'])){
                $params['master']['dbname'] = $compte->getBddName();
                $params['master']['user'] = $compte->getSqlUser();
                $params['master']['password'] = $compte->getSqlPassword();
            }
        }

        // Set up the parameters for the parent
        $clientConnection->__construct(
            $params, $clientConnection->getDriver(), $clientConnection->getConfiguration(),
            $clientConnection->getEventManager()
        );
```

This work perfectly if i don't configure any slaves (in config.yml), but does not work when i use slaves : 
First connection works well, but when connecting to an other account (in the same php session, overwriting client connection), it works only for the first item. The second connection seems not to be updates (without any errors).
It is as if there was a cache for doctrine dbal slaves connection that is not erase.

Any solution ? 

Thank you
