### ISSUE TITLE
[Request] Check if host exists in PDPMySql driver

### ISSUE THREAD

**Issue by fridde** [doctrine/dbal#2738]
I just spent two hours trying to debug a non-obvious mistake.

In my localhost dev environment, I had forgotten to provide a "host" value to the parameters given to 
`Doctrine\ORM\EntityManager::create($params, $config);`

While this created no problems on my local machine (why?), the time after deployment to the server was a debugging nightmare, since the stacktrace showed the rather misleading PDOException `SQLSTATE[HY000] [2002] No such file or directory`.

I'd love to see the check in [Doctrine\DBAL\Driver\PDOMySql\Driver::constructPdoDsn()](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php#L60) for `isset($params['host'])` extended with an `else` block of some sorts, maybe giving a notice or even throwing an error.

If there is a good argument against this check, I'd love to hear it. Maybe there are use cases for running mysql without a given host?

Below is a reduced example of my code that worked on my local machine, but not on the server:
#### settings.yml
```YAML
db_config:
  dev:
    db_host : 'localhost'
    db_name : 'my_local_database'
    db_username : 'root'
    db_password : ''
  prod:
    db_host : 'prod.mysql.myserver.com'
    db_name : 'my_remote_database'
    db_username : 'user_1234'
    db_password : 'hunter2'
```
#### index.php
```PHP
$prod_or_dev = 'prod'; // <-- this setting comes from somewhere else and changes

$yaml_array = \Symfony\Component\Yaml\Yaml::parse(file_get_contents('settings.yaml'));
$db_config = $yaml_array["db_config"][$prod_or_dev];


 $db_params = ['driver'=>'pdo_mysql', 'user'=> $db_config["db_username"],'password'=>$db_config['db_password'], 'dbname' =>$db_config['db_name']];
// OBSERVE THAT I FORGOT TO SET $db_params["host"]

$config = Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration('src/Entities/');
$EM = Doctrine\ORM\EntityManager::create($db_params, $config);

//testing
$user = $EM->getRepository('User')->find(1);
var_dump($user);
```
