### ISSUE TITLE
MySQL: Incorrect generation of decimal primary keys

### ISSUE THREAD

**Issue by fxOne** [doctrine/dbal#2829]
I defined in my `orm.yml`: 
```
SizeInformation:
  type: entity
  table: size_information
  id:
    width:
      type: decimal
      column: width
      precision: '6'
      scale: '2'
      nullable: false
```

Which generates the following SQL code with the Symfony `doctrine:migration:diff` command:
```
CREATE TABLE element_page_position_size_information (
  width NUMERIC(10, 0) NOT NULL,
  PRIMARY KEY(element_width)
)
```
Which is incorrect as I defined `NUMERIC(6, 2)`.
