### ISSUE TITLE
MySQL: Wrong order of generated primary keys

### ISSUE THREAD

**Issue by fxOne** [doctrine/dbal#2831]
I defined in my `address.orml.yml`:
```
Address:
  type: entity
  table: addresses

  id:
    user:
      id: true
      associationKey: true
      column: user_id
    addressType:
      id: true
      type: EnumAddressType
      nullable: false
      column: address_type

  fields:
    ....
```
Generates the following MySQL Code on the Symfony `doctrine:migration:diff` command:

```
CREATE TABLE addresses 
(address_type ENUM('billing','shipping') COMMENT '(DC2Type:EnumAddressType)' NOT NULL COMMENT '(DC2Type:EnumAddressType)', 
extranet_2level_customer_id INT NOT NULL,
...
PRIMARY KEY(address_type, user_id));
```
I would expect that the primary key would be `user_id, address_type`  as I defined it in this order.
Is this a bug or do I must define something else to get the primary key in my expected order?
