### ISSUE TITLE
[Symfony3] [mariadb] Cannot connect using SSL remotely

### ISSUE THREAD

**Issue by cayman54** [doctrine/dbal#2862]
Hi,
I try to configure symfony3 and dbal to connect to my remote mariadb database with ssl.
When i connect with the command `mariadb -u user -h xxx.xxx.xxx.xxx -p` it works fine.
But when I try from my symfony config I get this error :  
`PDO::__construct(): Cannot connect to MySQL by using SSL`  

My app/config/config.yml looks like this :  
```
driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        options:
            1012 : %ca_cert%
            1011 : %private_key%
            1010 : %public_cert%
```  
And my app/config/parameters.yml :  
```
parameters:
    database_host: xxx.xxx.xxx.xxx
    database_port: xxxx
    database_name: dbname
    database_user: user
    database_password: password
    private_key: /path/client-key.pem
    public_cert: /path/client-cert.pem
    ca_cert: /path/ca-cert.pem
```
I'm on a debain 9 server with php7.0 and php7.0-fpm -nginx installation)
Some help would be very appreciated...
Thanks,
