### ISSUE TITLE
Bug with server_version for MariaDB >10.2.7

### ISSUE THREAD

**Issue by tristanbes** [doctrine/dbal#2985]
Hello,

I think there is a problem when providing the `server_version` parameter.

when having a `server_version` set to `10.2.12`, the bug [discussed here](https://github.com/doctrine/dbal/pull/2825) is still present. (it generates endless migrations diff)

**When removing the `server_version` parameter, it works as excepted.**

```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: "%database_server_version%"  // << resolves to 10.2.12
```

We also tried
```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: 10.2.12 
```

Could it be that the excepted version is something else than 10.2.x ?
