### ISSUE TITLE
Column Definition Changed to NUMERIC from DECIMAL

### ISSUE THREAD

**Issue by mab05k** [doctrine/dbal#3403]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

After upgrading to v2.9, running `doctrine:schema:validate` command fails. Recommends changing my column definition from DECIMAL to NUMERIC.

#### Previous behaviour

Previous column definition
```sql
`column_name` DECIMAL(6,3) NOT NULL DEFAULT '1.000'
```

#### Current behavior

New Column Definition
```sql
`column_name` NUMERIC(6, 3) NOT NULL DEFAULT '1.000'
```

#### How to reproduce
This configuration was being used in a Symfony Application
Using MySQL 5.6
Run `bin/console doctrine:schema:create` with v2.8
Entity Mapping Configuration
```yaml
        column:
            type: decimal
            nullable: false
            precision: 6
            scale: 3
            column: column_name
            options:
                default: 1.000
```
Upgrade to v2.9 and run `doctrine:schema:validate` to reproduce.

I was able to verify that this is caused because of the "default" value set in "options". Removing this allowed Doctrine to continue to map this column as DECIMAL.
