### ISSUE TITLE
use Doctrine\DBAL\Event\Listeners\OracleSessionInit in Multiple databases type?

### ISSUE THREAD

**Issue by lcp0578** [doctrine/dbal#3681]
### Feature Request

When i use MySQL and Oracle, config `oracle.listener`
```
 oracle.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }
```
 but it always execute the code
```
// Doctrine\DBAL\Event\Listeners\OracleSessionInit.php
  /**
     * @return void
     */
    public function postConnect(ConnectionEventArgs $args)
    {
        if (! count($this->_defaultSessionVars)) {
            return;
        }

        array_change_key_case($this->_defaultSessionVars, CASE_UPPER);
        $vars = [];
        foreach ($this->_defaultSessionVars as $option => $value) {
            if ($option === 'CURRENT_SCHEMA') {
                $vars[] = $option . ' = ' . $value;
            } else {
                $vars[] = $option . " = '" . $value . "'";
            }
        }
        $sql = 'ALTER SESSION SET ' . implode(' ', $vars);
        $args->getConnection()->executeUpdate($sql);
    }
```
[config.yml detail](https://github.com/symfony/symfony/issues/33638)
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

So, I hope this service doesn't work when it's a MySQL connection.
