### ISSUE TITLE
column "min_value" does not exist dbal 2.10.2 with postgress 11.7

### ISSUE THREAD

**Issue by shubaivan** [doctrine/dbal#4002]
### Bug Report

I updated to **2.10.2** and faced with problem if using postgress 11.7

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     |2.10.2
#### Summary

I update my psql to version 11.7 and faced with error when try to create migration diff
I try to set 10, 11 and still had error

```
doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11'
```

```
  An exception occurred while executing 'SELECT min_value, increment_by FROM "products_id_seq"':  
                                                                                                  
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist                  
  LINE 1: SELECT min_value, increment_by FROM "products_id_seq"
```
#### Current behaviour

throwing error

#### How to reproduce

with  `"doctrine/dbal": "2.10.2", "symfony/orm-pack": "v1.0.8"` will execute `php bin/console doctrine:migrations:diff`
#### Expected behaviour

generate migration

**Comment by bozhidarc** [comment]
Same problem but with PostgreSQL 10.3.

**Comment by shubaivan** [comment]
I will try to change driver class but still faced with that error when try to execute migration diff or `messenger:failed:show `

looks my example please 

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: '~^(?!messenger_messages)~'
                driver_class: App\Doctrine\Driver\PDOPgSqlDriver
#                driver: 'pdo_pgsql'
                server_version: '10.5'
                charset: utf8


my class `src/Doctrine/Driver/PDOPgSqlDriver.php` 

```
<?php


namespace App\Doctrine\Driver;

use App\Doctrine\PostgreSQL100Platform;
use Doctrine\DBAL\Driver;
use Doctrine\DBAL\Driver\PDOPgSql\Driver as ParentDriver;

class PDOPgSqlDriver extends ParentDriver implements Driver
{
    public function createDatabasePlatformForVersion($version)
    {
        return new PostgreSQL100Platform();
    }
    
    public function getSchemaManager(\Doctrine\DBAL\Connection $conn)
    {
        return new Postgre10SqlSchemaManager($conn);
    }
}
```

and 
`src/Doctrine/Driver/Postgre10SqlSchemaManager.php`

```
<?php


namespace App\Doctrine\Driver;

use Doctrine\DBAL\Schema\PostgreSqlSchemaManager;
use Doctrine\DBAL\Schema\Sequence;

class Postgre10SqlSchemaManager extends PostgreSqlSchemaManager
{
    /**
     * {@inheritdoc}
     */
    protected function _getPortableSequenceDefinition($sequence)
    {
        if ($sequence['schemaname'] !== 'public') {
            $sequenceName = $sequence['schemaname'] . "." . $sequence['relname'];
        } else {
            $sequenceName = $sequence['relname'];
        }
        if ( ! isset($sequence['increment_by'], $sequence['min_value'])) {
            $data      = $this->_conn->fetchAssoc('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));
            $sequence += $data;
        }
        return new Sequence($sequenceName, $sequence['increment_by'], $sequence['min_value']);
    }
}
```


and 
`src/Doctrine/PostgreSQL100Platform.php`

```
<?php


namespace App\Doctrine;

use Doctrine\DBAL\Platforms\Keywords\PostgreSQL94Keywords;
use Doctrine\DBAL\Platforms\PostgreSQL94Platform;

/**
 * Provides the behavior, features and SQL dialect of the PostgreSQL 10.0 database platform.
 */
class PostgreSQL100Platform extends PostgreSQL94Platform
{
    /**
     * {@inheritdoc}
     */
    protected function getReservedKeywordsClass() : string
    {
        return PostgreSQL94Keywords::class;
    }
    public function getListSequencesSQL($database) : string
    {
        return 'SELECT sequence_name AS relname,
                       sequence_schema AS schemaname,
                       minimum_value AS min_value,
                       increment AS increment_by
                FROM   information_schema.sequences
                WHERE  sequence_catalog = ' . $this->quoteStringLiteral($database) . "
                AND    sequence_schema NOT LIKE 'pg\_%'
                AND    sequence_schema != 'information_schema'";
    }
}
```

But it's not works... every time my connection contains `\Doctrine\DBAL\Driver\PDOPgSql\Driver` instead my custom driver and I'm not understand why ... :(
I don't need some manually approach, only some way when code will be presetn in git. 
And idea ?
