### ISSUE TITLE
pg boolean conversion bug in 2.13.0

### ISSUE THREAD

**Issue by artagnon** [doctrine/dbal#4601]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.13.0

#### Summary

I have a symfony app on which I've installed symfony/orm-pack, and I get a `... WHERE u0_.deleted = 0` emitted in my db query where `u0_.deleted` is a boolean field. I've checked the code, and indeed, there seems to be extensive boolean handling for pdo_psql, so I don't know what's going on.

#### Current behaviour

I get a 500 on my site, and my logs report `ERROR:  operator does not exist: boolean = integer`

#### How to reproduce

In a symfony project, fill in the `doctrine.yaml` with the following code:

```
doctrine:
  dbal:
    driver: pdo_pgsql
    url: "%env(resolve:HEROKU_POSTGRESQL_MAROON_URL)%"
    charset: UTF8
    server_version: "13.2"
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
```

#### Expected behaviour

The emitted sql query should be `... WHERE u0_.deleted = 0` instead.
