### ISSUE TITLE
DBAL logging connection __destruct can be run after the logger has closed

### ISSUE THREAD

**Issue by dave-redfern** [doctrine/dbal#5340]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.4

#### Summary

The `DBAL\Logging\Connection` middleware uses `__destruct()` to call into the logger to log `Disconnecting` but when using syslog (or potentially any logger with a remote resource)  with monolog, the syslog connection can be terminated _before_ the DBAL middleware drops out of scope. This causes a fatal error from the monolog UdpSocket, halting execution:

Example stack trace:
```
PHP Fatal error:  Uncaught RuntimeException: The UdpSocket to syslog:514 has been closed and can not be written to anymore in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php:63
Stack trace:
#0 /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php(49): Monolog\Handler\SyslogUdp\UdpSocket->send()
#1 /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdpHandler.php(77): Monolog\Handler\SyslogUdp\UdpSocket->write()
#2 /app/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\SyslogUdpHandler->write()
#3 /app/vendor/monolog/monolog/src/Monolog/Logger.php(328): Monolog\Handler\AbstractProcessingHandler->handle()
#4 /app/vendor/monolog/monolog/src/Monolog/Logger.php(527): Monolog\Logger->addRecord()
#5 /app/vendor/doctrine/dbal/src/Logging/Connection.php(30): Monolog\Logger->info()
#6 [internal function]: Doctrine\DBAL\Logging\Connection->__destruct()
#7 {main}
```

#### Current behaviour

Exception terminating process, which if in docker entry point halts the image from running.

#### How to reproduce

 * start a new SF skeleton project (`composer create-project symfony/skeleton test-app`)
 * add monolog and doctrine (`composer req orm log`)
 * setup db connection (sqlite, pg whatever)
 * setup monolog with a syslog connection
```yaml
when@dev:
    monolog:
        handlers:
            main:
                type: syslogudp
                host: "syslog.server.host"
                port: "514"
                facility: local1
                ident: "test-app"
                level: debug
                channels: [ "!event" ]
``` 
 * add an entity with basic annotations
```php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public ?int $id = null;
    /**
     * @ORM\Column(type="string", length=255)
     */
    public string $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }
}
```
 * run `bin/console doctrine:schema:validate`
 * error with UdpSocket closed originating from `Doctrine\DBAL\Logging\Connection`

#### Expected behaviour

Logging middleware should not cause exceptions and can be prevented by removing the `__destruct()` logger call or wrapping in a try {} catch {}.
