### ISSUE TITLE
Configuration for read replicas are ignored

### ISSUE THREAD

**Issue by leticiaporto** [doctrine/dbal#5964]
|    Q        |   A
|------------ | -----
| Version     | 2.13.5

### Support Question

I configured the replicas on file **doctrine.yaml**. I intend that replica1 be used for read operations. But, this configuration is ignored when I try to do a GET request, for example. This configuration would be enough, or I need implement more things?

Besides, when I use the **replicas** option and try save anything, I receive the error **The EntityManager is closed**.

I am using Symfony 4.4, Doctrine Bundle 2.4.3 and PostgreSQL 12.

### File doctrine.yaml

```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: 12
                driver: pdo_pgsql
                replicas:
                    replica1:
                        url: '%env(resolve:DATABASE_R01_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```
