### ISSUE TITLE
Add support for creating unlogged PostgreSQL tables

### ISSUE THREAD

**Issue by f-lombardo** [doctrine/dbal#6044]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes

#### Summary

Add support for creating unlogged PostgreSQL tables:
https://www.postgresql.org/docs/current/sql-createtable.html

I'd suggest to add a boolean `unlogged` option to `default_table_options` doctrine configuration
https://www.doctrine-project.org/projects/doctrine-bundle/en/latest/configuration.html
For example:
```yaml
doctrine:
    dbal:
        default_table_options:
            unlogged: true
```

This option could be handled in `PostgreSQLPlatform::_getCreateTableSQL`
