### ISSUE TITLE
Custom platform is not used for connection

### ISSUE THREAD

**Issue by danielgelling** [doctrine/dbal#6523]
### Bug Report

dbal version: 4.1.1

#### Summary
Providing a custom platform to the dbal configuration is not used when determining the platform for the connection.

#### Current behaviour
The default platform based on the server_version of the connection is used.

#### How to reproduce
Add a custom platform to your connection in `doctrine.yaml` configuration:
```yaml
doctrine:
    dbal:
        platform_service: App\Doctrine\CustomPlatform
```

#### Expected behaviour
Expecting the connection to use `App\Doctrine\CustomPlatform` as platform instead of the platform determined by `Doctrine\DBAL\Driver::getDatabasePlatform()`

I already found and fixed the bug locally. Will create a PR.
